### ISSUE TITLE
[Flicks] Project 1 - Review my app!

### ISSUE THREAD

**Issue by hshssingh4** [hshssingh4/Flicks#2]
My app is complete. Please review. /cc @codepathreview

**Comment by codepathreview** [comment]
Your work is really amazing :tada: 

:+1: Nice work! The point of this homework was to get a chance to implement a TableView (one of the most common views in iOS) and to work with real data over the network (in this case from the Movies Database API).

Hm, it looks like you have not pushed your Podfile to your repo. We cannot install pod and review your code. So please remember to upload your Podfile!

Looking at your gif, I see that the Collection View is another page. This is not really what we want. The Collection View and Table View should be on the same page. You may consider using the hide property to show and hide the Table View/CollectionView.

A key part of these projects is that you add additional features and tweak the UI / UX because that will provide the most learning opportunities. We encourage you to complete the projects early each week with the required stories and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

We have a detailed [Project 1 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_1_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

**Comment by hshssingh4** [comment]
I have added the Podfile. If there is anything else I should push to Github, please let me know. Sincere apologies for the mistake I made! I will soon make the other changes too.

**Comment by chieger** [comment]
Hi Harpreet! Your app looks amazing! This is a great submission. You can continue to experiment with some of the changes that were suggested, but you app is a complete and excellent submission as is. There is no further action required for Part 1.

Charlie
