### ISSUE TITLE
[Flicks] Project 2 - Review my app!

### ISSUE THREAD

**Issue by hshssingh4** [hshssingh4/Flicks#3]
My Flicks Part II is complete, please review. /cc @codepathreview

**Comment by minhkhang1795** [comment]
You app is so cool :100: We will share your app demonstration (a.k.a gif file) with other students as an inspiration for hard work! :sunglasses: 

The point of this homework was to get familiar with two common forms of navigation in iOS (push and tab bar). It also provided a chance to extend your Flicks app in new ways.

Your SVProgressHUD will appear and disappear instantly instead of waiting until the data are loaded from the network (you can check this by adding 3 breakpoints and see your app runs). You should put `SVProgressHUD.dismiss()` inside your network request:

``` Swift
// In your loadMoviesData() function:
let task : NSURLSessionDataTask = session.dataTaskWithRequest(request,
            completionHandler: { (dataOrNil, response, error) in
            SVProgressHUD.dismiss()
            ...
});
task.resume()
```

For an optional feature "load the low resolution image first then switch to the high resolution image when complete," there is a hidden, tricky part: if the high resolution image is already downloaded (the large image is cached from the network), then you should show the large image instantly instead of showing the low image then switch to the larger one. I surely believe you could figure the way to do so.

We have a detailed [Project 2 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_2_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

Best,
Khang
_CodePath Grader_

**Comment by hshssingh4** [comment]
Thank you so much. Such comments are so motivational! I will work even harder on my apps from now on!
